#!/usr/bin/python3

# name: nad_pscy (stands for "Plesk Server Check")
# purpose: Do a check of resources and domain use for a Plesk server.
# date: 2/22/2025, 7:49:00 PM
# author: elemental88keys
# status: v. 2: In addition to doing system resource and service plan checks, outdated WordPress components for domains are checked as well, then indicated in a list with the domain owner's name and email.

# [0] Important imports...
import psutil, statistics, time, subprocess, math

print(" -- System Resource Check -- ")
def asking_for_help():
    print("Usage: python3 new_pscy.py [OPTIONS]")
    print("OPTIONS:")
    print("-h, --help\t\tShow this help message and exit")
    print("-l, --log\t\tLog the check you've just made")
    print("Here's an example: nad_psc -h")
    print("Here's a logging example: nad_psc -l <log_file>")
    print("If you need to see this again, just write 'nad_psc -h' at the command line")

def cpu_load(percentage):
    match percentage:
        case x if x < 70:
            print("CPU Status: HEALTHY")
        case _:
            print("CPU Status: NOT HEALTHY")

# [1] Getting CPU information...
print("Getting CPU information...")
cpu_percentages = [psutil.cpu_percent(interval=1) for i in range (10)]
cpu_percent_avg = statistics.mean(cpu_percentages)
cpu_load(cpu_percent_avg)

# [2] Getting RAM information...
def mem_load(percentage):
    match percentage:
        case x if x < 70:
            print("MEM Status: HEALTHY")
        case _:
            print("MEM Status: NOT HEALTHY")

def mem_monitor(interval=1, amount=10):
    print(f"Getting RAM information...")
    mem_readings = []
    for i in range(0, amount):
        mem = psutil.virtual_memory()
        mem_reading = {
            "percentage": mem.percent,
            "used": mem.used,
            "total": mem.total
        }
        mem_readings.append(mem_reading)
        time.sleep(interval)

    return mem_readings

mem_monitor_results = mem_monitor()
mem_percentages = [mem_monitor_results[i]["percentage"] for i in range(10)]
mem_percent_avg = statistics.mean(mem_percentages)
mem_load(mem_percent_avg)

# [3] Getting Swap Information...
def swap_load(percentage):
    match percentage:
        case x if x < 70:
            print("SWAP Status: HEALTHY")
        case _:
            print("SWAP Status: NOT HEALTHY")

def swap_monitor(interval=1, amount=10):
    print("Getting SWAP information...")
    swap_readings = []
    for i in range(0, amount):
        swap = psutil.swap_memory()
        swap_reading = {
            "percentage": swap.percent,
            "used": swap.used,
            "total": swap.total
        }
        swap_readings.append(swap_reading)
        time.sleep(interval)

    return swap_readings

swap_monitor_results = swap_monitor()
swap_percentages = [swap_monitor_results[i]["percentage"] for i in range(10)]
swap_percent_avg = statistics.mean(swap_percentages)
swap_load(swap_percent_avg)

# [4] Plesk Checks...
# [4-1] Service plan checks...
# [4-1-1] Getting a list of all the subscriptions on the server...
subscription_list = subprocess.run(["sudo", "plesk", "bin", "subscription", "--list"], capture_output=True, text=True).stdout.split('\n')
def sum_disk_space(disk_space_list):
    total_disk_space = 0
    for disk_space in disk_space_list:
        disk_space_value, disk_space_unit = disk_space.split()
        if disk_space_unit == "B": total_disk_space += float(disk_space_value) / 1024 / 1024 / 1024
        elif disk_space_unit == "KB": total_disk_space += float(disk_space_value) / 1024 / 1024
        elif disk_space_unit == "MB": total_disk_space += float(disk_space_value) / 1024
        elif disk_space_unit == "GB": total_disk_space += float(disk_space_value)
        elif disk_space_unit == "TB": total_disk_space += float(disk_space_value) * 1024
        elif disk_space_unit == "unlimited": return "unlimited"
        else: return "ERROR: UNRECOGNIZED UNIT"
    return f"{round(total_disk_space, 2)} GB"

def convert_bytes(value, unit):
    # PURPOSE: Converts the value of disk space or traffic to bytes for easier comparison. It takes in the value and unit as parameters and returns the value in bytes. If the unit is "unlimited", it returns infinity. If an unrecognized unit is encountered, it returns an error message.
    if unit in ["B", "B/month"]: return float(value)
    elif unit in ["KB", "KB/month"]: return float(value) * 1024
    elif unit in ["MB", "MB/month"]: return float(value) * pow(1024,2)
    elif unit in ["GB", "GB/month"]: return float(value) * pow(1024,3)
    elif unit in ["TB", "TB/month"]: return float(value) * pow(1024,4)
    elif unit == "unlimited": return float('inf')
    else: return -1

def compare_disk_space(sp_disk_space, actual_disk_space):
    if len(sp_disk_space) == 0 or len(actual_disk_space) == 0: return "ERROR: COULD NOT GET DISK SPACE INFORMATION"
    sp_disk_space_value, sp_disk_space_unit = sp_disk_space.split()
    actual_disk_space_value, actual_disk_space_unit = actual_disk_space.split()
    sp_disk_space_value = convert_bytes(sp_disk_space_value, sp_disk_space_unit)
    actual_disk_space_value = convert_bytes(actual_disk_space_value, actual_disk_space_unit)
    if sp_disk_space_value == -1 or actual_disk_space_value == -1: return "ERROR: UNRECOGNIZED UNIT"
    elif sp_disk_space_value == float('inf'): return "HEALTHY"
    elif actual_disk_space_value == float('inf'): return "NOT HEALTHY"
    elif actual_disk_space_value <= sp_disk_space_value: return "HEALTHY"
    else: return "NOT HEALTHY"

def compare_traffic(sp_traffic, actual_traffic):
    if len(sp_traffic) == 0 or len(actual_traffic) == 0: return "ERROR: COULD NOT GET TRAFFIC INFORMATION"
    sp_traffic_value, sp_traffic_unit = sp_traffic.split()
    actual_traffic_value, actual_traffic_unit = actual_traffic.split()
    actual_traffic_unit = actual_traffic_unit.replace('Month','month')
    sp_traffice_value = convert_bytes(sp_traffic_value, sp_traffic_unit)
    actual_traffic_value = convert_bytes(actual_traffic_value, actual_traffic_unit)
    if sp_traffice_value == -1 or actual_traffic_value == -1: return "ERROR: UNRECOGNIZED UNIT"
    elif sp_traffice_value == float('inf'): return "HEALTHY"
    elif actual_traffic_value == float('inf'): return "NOT HEALTHY"
    elif actual_traffic_value <= sp_traffice_value: return "HEALTHY"
    else: return "NOT HEALTHY"

def check_domain_update_status(domain_name):
    """
    PURPOSE: Checks for the update status of the domain to then indicate whether or not the owner of the domain would need to be contacted to update their sites before we have to suspend it in 15 days.
    AUTHOR: nadits
    DATE: 3/11/2026 6:04 PM
    STATUS: --|--
    """
    pass

print()
print(" -- Service Plan Checks -- ")
for subscription in subscription_list:
    # [4-1-2] Getting the service plan for each subscription...
    sp_cmd = f'''sudo plesk bin subscription -i "{subscription}" | grep "NAD ITS - Tier" | cut -d ' ' -f 9-13 | sed 's/"//g' '''
    subscription_service_plan = subprocess.run(sp_cmd, shell=True, capture_output=True, text=True).stdout.strip()
    # print(subscription, subscription_service_plan)
    if subscription_service_plan != '':
        sp_info_ds_cmd = f'''sudo plesk bin service_plan --info "{subscription_service_plan}" | head -n 47 | tail -n 33 | grep "Disk space" | awk '{{print $3, $4}}' '''
        tier_sp_disk_space = subprocess.run(sp_info_ds_cmd, shell=True, capture_output=True, text=True).stdout.strip()
        # print(tier_sp_disk_space)
        sp_info_trf_cmd = f''' sudo plesk bin service_plan --info "{subscription_service_plan}" | head -n 47 | tail -n 33 | grep "Traffic" | awk '{{print $2, $3}}' '''
        tier_sp_traffic = subprocess.run(sp_info_trf_cmd, shell=True, capture_output=True, text=True).stdout.strip()
        # print(tier_sp_traffic)
        actual_info_ds_cmd = f'''sudo plesk bin subscription -i "{subscription}" | grep "Disk space used by " | awk '{{print $(NF-1), $NF}}' | sed 's/reports://g' '''
        actual_info_ds = subprocess.run(actual_info_ds_cmd, shell=True, capture_output=True, text=True).stdout.strip().split('\n')
        # print(actual_info_ds)
        # print(f"Actual disk space for {subscription}: {actual_info_ds}")
        actual_info_trf_cmd = f'''sudo plesk bin subscription -i "{subscription}" | grep "Traffic:" | awk '{{print $2, $3}}' '''
        actual_info_trf = subprocess.run(actual_info_trf_cmd, shell=True, capture_output=True, text=True).stdout.strip()
        # print(actual_info_trf)
        # print(len(actual_info_ds))
        if len(actual_info_ds) <= 1 and actual_info_ds[0] == '': ds_result = "ERROR: COULD NOT GET ACTUAL DISK SPACE"
        else: ds_result = compare_disk_space(tier_sp_disk_space, sum_disk_space(actual_info_ds))
        # print(tier_sp_disk_space, actual_info_trf)
        trf_result = compare_traffic(tier_sp_traffic, actual_info_trf)
        print(f"{subscription} - Disk Space: {ds_result} | Traffic: {trf_result}")

from typing import Any,List

def longest_per_column(data: List[List[Any]]) -> List[int]:
    """
    Returns a list where each index contains the length
    of the longest string in that column.

    Runs in O(n) time where n = total number of elements.
    """
    if not data:
        return []

    # Determine max number of columns
    col_count = max(len(row) for row in data)

    # Initialize max lengths
    max_lengths = [0] * col_count

    # Single pass through all cells
    for row in data:
        for col_index, value in enumerate(row):
            length = len(str(value))
            if length > max_lengths[col_index]:
                max_lengths[col_index] = length

    return max_lengths

# WP-Toolkit Check..
print()
print(" -- WordPress Updates Check -- ")

def print_outdated_table(array: List[List[Any]]) -> List[int]:
    column_lengths = [i if i > 0 else 25 for i in longest_per_column(array)]
    print("Reseller Name".ljust(column_lengths[0]), "Customer Name".ljust(column_lengths[1]), "Reseller Email".ljust(column_lengths[2]), "Customer Email".ljust(column_lengths[3]), "State".ljust(column_lengths[5]), "URL".ljust(column_lengths[6]))
    print("--".ljust(column_lengths[0]), "--".ljust(column_lengths[1]), "--".ljust(column_lengths[2]), "--".ljust(column_lengths[3]), "--".ljust(column_lengths[5]), "--".ljust(column_lengths[6]))
    for row in array:
        print(row[0].ljust(column_lengths[0]), row[1].ljust(column_lengths[1]), row[2].ljust(column_lengths[2]), row[3].ljust(column_lengths[3]), row[5].ljust(column_lengths[5]), row[6].ljust(column_lengths[6]))

plesk_wp_toolkit_command = r"""sudo plesk ext wp-toolkit --list | awk '{print $3,$5,$8}' | column -t | grep -v Working | grep Outdated | sed 's/https:\/\/\///g'"""
wp_toolkit_output = subprocess.run(plesk_wp_toolkit_command, shell=True, capture_output=True, text=True).stdout.split()
wp_toolkit_output = [wp_toolkit_output[i:i+3] for i in range(0, len(wp_toolkit_output), 3)][1:len(wp_toolkit_output)-1]
for piece_of_output in wp_toolkit_output:
    # Getting the usernames for the owners of the domains that need to be updated...
    piece_of_output[2] = piece_of_output[2].replace("https://www.","")
    subscription_info_cmd = f'''sudo plesk bin subscription -i "{piece_of_output[2]}" | grep "Owner's contact name:" | awk '{{print $NF}}' | sed 's/(//g' | sed 's/)//g' '''
    subscription_info_output = subprocess.run(subscription_info_cmd, shell=True, capture_output=True, text=True).stdout.strip()
    piece_of_output.append(subscription_info_output)

    # Getting the emails for the owners of the domains that need to be updated...
    customer_owner_info_cmd = f'''sudo plesk bin client -i "{piece_of_output[3]}" | grep "Email" | awk '{{print $NF}}' '''
    customer_owner_info_output = subprocess.run(customer_owner_info_cmd, shell=True, capture_output=True, text=True).stdout.strip()
    piece_of_output.insert(0, customer_owner_info_output)

    reseller_owner_info_cmd = f'''sudo plesk bin reseller -i "{piece_of_output[4]}" | grep "Email" | awk '{{print $NF}}' '''
    reseller_owner_info_output = subprocess.run(reseller_owner_info_cmd, shell=True, capture_output=True, text=True).stdout.strip()
    piece_of_output.insert(0, reseller_owner_info_output)

    # Getting the names of the owners of the domains that need to be updated...
    # print(piece_of_output)
    customer_owner_name_cmd = f'''sudo plesk bin client -i "{piece_of_output[5]}" | grep "Personal name:" | cut -d: -f2- | xargs'''
    customer_owner_name_cmd_output = subprocess.run(customer_owner_name_cmd, shell=True, capture_output=True, text=True).stdout.strip()
    piece_of_output.insert(0, customer_owner_name_cmd_output)

    reseller_owner_name_cmd = f'''sudo plesk bin reseller -i "{piece_of_output[6]}" | grep "Personal name:" | cut -d: -f2- | xargs'''
    reseller_owner_name_cmd_output = subprocess.run(reseller_owner_name_cmd, shell=True, capture_output=True, text=True).stdout.strip()
    piece_of_output.insert(0, reseller_owner_name_cmd_output)

    # Print output...
    # print(format_output(piece_of_output))

# print(longest_per_column(wp_toolkit_output))
print(print_outdated_table(wp_toolkit_output))
